### ISSUE TITLE
Blocked on Implementing ValidationGroup and CauseValidation

### ISSUE THREAD

**Issue by Kahbazi** [FritzAndFriends/BlazorWebFormsComponents#36] opened 2020-01-14 16:21 UTC
In order to implement `ValidationGroup` and `CauseValidation`, we need to get the element causing submit in `EditForm`, which is not possible in blazor right now. 
I opened an issue on AspNetCore repo requesting this feature. https://github.com/dotnet/aspnetcore/issues/18326

**Comment by csharpfritz** [comment] 2020-01-14 19:09
I'll show this on stream Thursday the 16th and we can discuss alternate paths forward

**Comment by hishamco** [comment] 2020-02-26 11:21
An updates on this one?

**Comment by csharpfritz** [comment] 2020-02-26 16:25
Nothing yet...  will re-evaluate next week

**Comment by hishamco** [comment] 2020-09-05 00:18
Duplicate of #247

**Closed by hishamco** 2020-09-05 00:18 UTC
Labels: blocked, duplicate, help wanted
